name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
