name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and SDL
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev 
        


    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
        
    - name: Run program 1
      run: |
        cd build
        cd bin
        ./dz
        ./hello_dynamic
        ./hello_static
        
    - name: Run program 2
      run: |
        cd build
        cd bin
        ./sdl_dynamic
        ls 
        # ./sdl_static
