name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and SDL
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake 
        sudo apt install git
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        
        sudo cmake -S . -B build 
        sudo cmake -DSDL_STATIC_ENABLED_BY_DEFAULT=ON ..
        sudo cmake --build build 
        sudo cmake --install build

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
        
    - name: Run program 1
      run: |
        cd build
        cd bin
        ./dz
        ./hello_dynamic
        ./hello_static
        
    - name: Run program 2
      run: |
        cd build
        cd bin
        ./sdl_shared
        ./sdl_static
