name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and SDL2
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev 
        
    - name: Install SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL
        cd SDL
        mkdir build
        cd build
        cmake .. -DSDL_STATIC=ON
        cmake --build .
        sudo cmake --install .

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
        
    - name: Run program 1
      run: |
        cd build
        cd bin
        ./dz
        ./hello_dynamic
        ./hello_static
        
    - name: Run program 2
      run: |
        cd build
        cd bin
        ls -lh sdl_static
        ls -lh sdl_dynamic
        
        
